.gitignore, requirements.txt, src/charm.py, src/tempo.py, tox.ini
promtail tries to use port 9095 for its grpc listen server, but tempo has already snatched it.
This PR sets a different grpc listen port for Tempo.
=> Fix grpc port conflict

lib/charms/tempo_k8s/v0/charm_instrumentation.py, lib/charms/tempo_k8s/v0/tracing.py, src/charm.py, tests/interface/conftest.py, tests/scenario/conftest.py, tests/scenario/test_charm_instrumentation.py, tests/scenario/test_tracing_provider.py
- adds an `endpoint_removed` event for charm usage
- no longer raises exceptions when databag contents are invalid
- public `is_ready` check for charm usage
=> Endpoint removed handling

charmcraft.yaml, requirements.txt
Charm fails on install hook:
```
File "/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/grpc/_compression.py", line 20, in <module>
from grpc._cython import cygrpc
ImportError: cannot import name 'cygrpc' from 'grpc._cython' (/var/lib/juju/agents/unit-tempo-k8s-0/charm/venv/grpc/_cython/__init__.py)
```
The issue is that we are running on 20.04 (py38), but the cygrpc name is for a py310:
```
root@tempo-0:/var/lib/juju# find / -type f -name "cygrpc*"
/var/lib/juju/agents/unit-tempo-0/charm/venv/grpc/_cython/cygrpc.cpython-310-x86_64-linux-gnu.so
root@tempo-0:/var/lib/juju# cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
```
Build on and run on 22.04 only.
Fixes #37.
It is possible that this is a result of moving packages to `charm-binary-python-packages`. Haven't …
=> Build on and run on 22.04 only

lib/charms/tempo_k8s/v0/charm_tracing.py, tests/integration/tester/src/charm.py, tests/interface/conftest.py
Follow up on #43 with more renames (doc fix).
=> [doc] replace `charm_instrumentation` with `charm_tracing`

lib/charms/tempo_k8s/v0/tracing.py
Tracing LIBPATCH is too high, 0.8.
The ERROR downgrade [didn't get published](https://github.com/canonical/tempo-k8s-operator/actions/runs/6160893608/job/16718862727#step:3:58) to charmhub because we overbumped LIBPATCH
```
Library charms.tempo_k8s.v0.tracing has a wrong LIBPATCH number, it's too high and needs to be consecutive, Charmhub highest version is 0.6.
```
Sync with charmhub, 0.7.
=> Sync tracing LIBPATCH

lib/charms/tempo_k8s/v1/charm_tracing.py, tests/scenario/test_charm_tracing.py
Reduce log spam on tracer context variable lookup. These logs aren't relevant in most cases.
Fixes #66
=> Reduce log spam on looking up tracer

src/charm.py
There's a transient error status on tempo startup as charm-tracing lib races with tempo startup.
Add an `is_ready` guard before exposing tempo endpoint.
=> Check if tracing is ready before exposing its endpoint in tempo charm

HACKING.md, README.md, lib/charms/tempo_k8s/v2/tracing.py, metadata.yaml, src/charm.py, src/tempo.py
Upgrade Tempo to the latest image (2.4.0).
Run `charmcraft pack` on the charm and run the following commands:
```
juju deploy cos-lite --trust --channel edge
juju deploy ./tempo-k8s_ubuntu-22.04-amd64.charm tempo --resource tempo-image=grafana/tempo:2.4.0
(once everything settles down)
jhack imatrix fill
```
Bundle:
```
bundle: kubernetes
applications:
alertmanager:
charm: alertmanager-k8s
channel: edge
revision: 103
series: focal
resources:
alertmanager-image: 87
scale: 1
constraints: arch=amd64
storage:
data: kubernetes,1,1024M
trust: true
catalogue:
charm: catalogue-k8s
channel: edge
revision: 33
series: focal
resources:
catalogue-image: 32
scale: 1
options:
description: "Canonical Observability Stack Lite, or COS Lite, is a light-weight,
highly-integrated, \nJuju-based observability …
```
=> Upgrade Tempo to 2.4.0 with adjusting config properties/defaults

src/grafana_dashboards/tempo.json
There was an issue with the newly created dashboard - its first row was marked as uncollapsed, which caused all the internal panels to disappear altogether. It looks like this was a known _feature_ of Grafana that removes panels that are inside of a row if that row is `collapsed: false`: https://github.com/grafana/grafana/issues/34565#issuecomment-945623278
I've also noticed a misleading name of one of the dashboard panels plus a couple of styling issues.
Move "at a glance" row panels outside of the row structure so that Grafana knows to always render them. It is possible to hide them afterwards but it seems this is the way to go with Grafana panels.
Deploy tempo + cos-lite, run `jhack imatrix fill`.
=> Uncollapse first panel in tempo dashboard

tox.ini
When using with the most recent version of pytest 8.2.0, asyncio-0.21.1 is used which breaks the fixtures with error: AttributeError: 'FixtureDef' object has no attribute 'unittest'.
https://github.com/charmed-kubernetes/pytest-operator/issues/131
Use pytest version < 8.2.0 for our tests until upstream is fixed.
=> use pytest version < 8.2.0

charmcraft.yaml, lib/charms/tempo_k8s/v2/tracing.py, lib/charms/traefik_route_k8s/v0/traefik_route.py, src/charm.py, src/tempo.py, tests/scenario/test_ingressed_tracing.py, tests/scenario/test_tracing_legacy.py, tests/scenario/test_tracing_requirer.py, tests/unit/test_charm.py, tests/unit/test_tempo.py
Tempo receiver endpoints were not accessible over traefik as they are bound to different ports. Fixes #82 
Use `traefik_route` with changes introduced in [traefik-k8s-operator#325](https://github.com/canonical/traefik-k8s-operator/pull/325) to define ports traefik needs to open.
Also fix creating URLs for tracing consumers that use `external_url` - scheme and port were missing from the created url.
This change is needed for cross-model traces to work. They cannot access internal endpoints of a different k8s cluster . No traces were also coming from machine models.
Run the following bundle and verify endpoints (example, port 3200, `/metrics`, port 4318 (expected prometheus metrics), `/v1/traces` (expected HTTP code 405)) are accessible on traefik's external IP.
```
bundle: kubernetes …
```
=> Add traefik_route to serve tracing endpoints through ingress if it exists

src/tempo.py
Traces seem to disappear after a longer period.
Set default `block_retention` to 30 days. Set also `compacted_block_retention` that says how long blocks should stay around after they've been compacted
See https://github.com/grafana/tempo/blob/main/modules/compactor/config.go#L38 and https://grafana.com/docs/tempo/latest/configuration/#compactor for context.
- deploy tempo with something that posts traces
- keep it running for more than 1h
- you should still see the original traces
=> Set total block retention to 30 days

lib/charms/tempo_k8s/v1/charm_tracing.py, tests/scenario/test_charm_tracing.py
Fixes #120 
Try both
- fixed issue in charm tracing lib that would incorrectly wrap staticmethods depending on how they're called
=> fix for #120

src/charm.py, src/tempo.py, tests/scenario/test_charm.py
When tempo receives tracing-relation-created before pebble-ready it tries to start a service that hasn't been defined yet.
guard the Tempo.restart() paths with checks that verify that the service is defined
=> Fix race between pebble-ready and relation-created

lib/charms/tempo_k8s/v2/tracing.py
This PR adds a utility function to the tracing lib.
Other libraries that offer a tracing endpoint that could be used by charm_tracing could implement a function with the same signature so that charms can use this logic with minimal boilerplate.
Fixes #121
=> tracing util for charm_tracing

lib/charms/tempo_k8s/v1/charm_tracing.py, tests/integration/test_integration.py, tests/scenario/test_charm_tracing.py
Fixes #88 
If you deploy `grafana-k8s` as `grafana`, the service name for charm traces was 'grafana'. The traces generated by the grafana workload also had the same service name, resulting in confusion.
Service name for the charm tracer will now default to `<app name>-charm` so a conflict with the workload service name is less likely.
=> add service name -charm prefix

lib/charms/tempo_k8s/v1/charm_tracing.py, tests/integration/test_integration.py, tests/scenario/test_charm_tracing.py
Fixes #111 
right now all charm traces that show up in grafana have the same title: `charm exec`. 
Not very descriptive.
Now it looks like `<unit-name>: <event> event`, for example `loki/1: foo-relation-changed event`
=> changed root span name to be more descriptive

lib/charms/tempo_k8s/v1/charm_tracing.py, tests/scenario/test_charm_tracing.py
This PR adds support for charm_tracing to grab the endpoint and cert it needs from instance attributes instead of properties and methods.
This is a nicety which in combination with #135 means any charm can enable/disable charm tracing and correctly configure it with/without TLS with a single line of code (plus the decorator).
before:
```
from lib....charm_tracing import charm_tracing
@charm_tracing(tracing_endpoint="foo", server_cert="bar")
class MyCharm(...):
[...]
def foo(self):
return ... 
def bar(self):
return ...
```
after:
```
from lib....charm_tracing import charm_tracing
from lib....tracing import charm_tracing_config
@charm_tracing(tracing_endpoint="foo", server_cert="bar")
class MyCharm(...):
def __init__(...):
self.tracing = TracingEndpointRequirer(...)
self.foo, self.bar = …
```
=> instance attribute support for charm_tracing forward-declared definitions

tests/scenario/test_charm_tracing.py
We didn't have tests for charm_tracing on inherited methods.
Now we do.
=> added test for autoinstrumentation on inherited methods

lib/charms/tempo_k8s/v2/tracing.py
This helps address issue #https://github.com/canonical/tempo-coordinator-k8s-operator/issues/8
=> removed excess receiver protocols from enum

src/charm.py, tests/scenario/conftest.py, tests/scenario/test_charm.py
On sleep/resume, the tempo charm goes into error because it receives a custom notice event for a service that doesn't exist in pebble (yet)?
Unclear what's causing this, but it's a pain.
Workaround and test included.
=> Fix resume error

lib/charms/tempo_k8s/v1/charm_tracing.py, lib/charms/tempo_k8s/v2/tracing.py, pyproject.toml, src/charm.py, src/tempo.py, tests/integration/test_ingressed_tls.py, tests/integration/test_tls.py, tests/interface/conftest.py, tests/scenario/conftest.py, tests/scenario/helpers.py, tests/scenario/test_charm.py, tests/scenario/test_ingressed_tracing.py, tests/scenario/test_tls.py, tests/scenario/test_tracing_requirer.py, tests/unit/test_charm.py, tests/unit/test_tempo.py
#157
This PR takes the solution from #151 and:
* runs it before importing any opentelemetry packages
* widens it to apply to all opentelemetry packages
While fixing this PR, I noticed the ruff.lint settings in pyproject.toml were under an incorrect array ([lint] instead of [tool.ruff]/[tool.ruff.lint]).  I've fixed that plus any linting errors that came up as a result as a drive-by.
#151
(in a machine model)
to repro the original issue
```
charmcraft pack
juju deploy grafana-agent --revision=134 --channel=latest/stable
juju deploy ubuntu
juju relate grafana-agent ubuntu
juju refresh grafana-agent --path ./grafana-agent_ubuntu-22.04-amd64.charm
juju refresh grafana-agent --channel latest/edge
```
to demo the fix:
```
juju deploy grafana-agent --revision=134 --channel=latest/stable
juju …
```
=> fix: remove stale opentelemetry_sdk packages at lib module import time

lib/charms/tempo_k8s/v1/charm_tracing.py, src/charm.py, tests/integration/test_ingressed_tls.py, tests/integration/test_tls.py, tests/interface/conftest.py, tests/scenario/conftest.py, tests/scenario/helpers.py, tests/scenario/test_a_charm_tracer_multi_import_warning.py, tests/scenario/test_charm.py, tests/scenario/test_charm_tracer_multi_import_warning.py, tests/scenario/test_charm_tracing.py, tests/scenario/test_ingressed_tracing.py, tests/scenario/test_tls.py, tests/scenario/test_tracing_requirer.py, tests/unit/test_charm.py, tests/unit/test_tempo.py
Fixes #60 
Added a warning if we're detecting a double import situation.
https://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-double-import-trap
Added a test verifying the warning behaviour.
=> solution and test for tracer multi-import issue

tests/interface/conftest.py, tests/interface/test_tracing.py
Interface tests for `tracing` with tempo-k8s charm are failing with:
```
ERROR    pytest_interface_tester:plugin.py:330 Interface tester plugin failed with Uncaught exception (<class 'RuntimeError'>) in operator/charm code: RuntimeError('400 Bad Request: service "tempo-ready" does not exist')
```
Add tempo-ready service to conftest.py used by interface tests.
This change fixes only `tracing/v2` tests - previous versions fail due drop in support in #108. A separate PR to charm-relation-interfaces will follow, dropping support for previous tracing versions in tempo-k8s together with other test changes.
=> Add tempo-ready service for interface tests

lib/charms/tempo_k8s/v2/tracing.py, tests/scenario/test_charm_tracing.py, tox.ini
Fixes #169 
Add documentation to use the `is_ready` safeguard before `get_endpoint` to prevent permission denied exceptions due to non-leader units trying to access local app databags.
=> Add using `is_ready` safeguard to `get_endpoint` docstring
